version: 0.0
os: linux
files:
  - source: /
    destination: /apps/zennvote-backend-v3
permissions:
  - object: /apps/zennvote-backend-v3
    pattern: "**"
    owner: "ubuntu"
    mode: 644
    type:
      - file