name: Test Only [develop branch]

on:
  push:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependancies
      run: npm install

    - name: Test project
      run: npm test